PREFIX qqq-inst: <http://www.q8onto.org/healthcareOntology/resource/>
PREFIX qqq: <http://www.q8onto.org/healthcareOntology.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

SELECT ?appointment ?appointmentID ?patient ?clinician ?startTime ?endTime ?status
WHERE {
	?appointment a <http://www.q8onto.org/healthcareOntology.owl#Appointment> .
	?appointment qqq:hasAppointmentID ?appointmentID .
	?appointment qqq:hasPatient ?patient .
	?appointment qqq:hasClinician ?clinician .
	?appointment qqq:hasStartTime ?startTime .
	?appointment qqq:hasStartTime ?endTime .
	?appointment qqq:hasStatus ?status .
}
