PREFIX qqq-inst: <http://www.q8onto.org/healthcareOntology/resource/>
PREFIX qqq: <http://www.q8onto.org/healthcareOntology.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

SELECT ?waitingList ?waitingListID ?waitingListType ?patient ?arrivalTime ?clinician ?department ?priorityLevel ?comment ?status
WHERE {
	?waitingList a <http://www.q8onto.org/healthcareOntology.owl#WaitingList> .
	?waitingList qqq:hasWaitingListID ?waitingListID .
	?waitingList qqq:hasWaitingListType ?waitingListType .
	?waitingList qqq:hasPatient ?patient .
	?waitingList qqq:hasArrivalTime ?arrivalTime .
	?waitingList qqq:hasClinician ?clinician .
	?waitingList qqq:hasDepartment ?department .
	?waitingList qqq:hasPriorityLevel ?priorityLevel .
	?waitingList qqq:hasComment ?comment .
	?waitingList qqq:hasStatus ?status .
}
